---
name: Create and publish a Docker image

on:
  workflow_dispatch:
  repository_dispatch:
    types: [rebuild]
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    uses: ffbuilds/.github/.github/workflows/docker.yml@main
    with:
      push_images: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

