---
name: Create and publish a Docker image

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    uses: ffbuilds/.github/.github/workflows/docker.yml@main
